# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from ipywidgets.embed import embed_minimal_html as export


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
Vacay_Data = pd.read_csv("Resources/city_data.csv")
Vacay_Data.dropna(inplace = True)
Vacay_Data.head()

,City,Country,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Date
0,jamestown,US,42.10,-79.24,32.00,93,1,5.75,1610684981
1,puerto ayora,EC,-0.74,-90.35,73.99,93,47,4.00,1610684984
2,horta,PT,38.53,-28.63,62.31,87,95,29.48,1610684984
3,marcona,PF,-23.12,-134.97,78.30,74,14,10.18,1610684822
4,rikitea,BR,-17.71,-39.25,74.35,86,0,4.03,1610684985

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)
locations = Vacay_Data[["Latitude","Longitude"]]
humidity = Vacay_Data["Humidity"].astype(float)

In [4]:
fig = gmaps.figure()



# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1,opacity=1)


# Add layer
fig.add_layer(heat_layer)

export("Heatmap_Outputs/heatmap.html",views = [fig])

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
#A max temperature lower than 80 degrees but higher than 70.
first = Vacay_Data.loc[Vacay_Data["Temperature"] < 80,:]
second = first.loc[first["Temperature"]>70,:]
third = second.loc[second["Wind Speed"]<10,:]
fourth = third.loc[third["Cloudiness"]==0,:]

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = pd.DataFrame()
fifth = pd.DataFrame(fourth)
hotel_df['City'] = fifth['City']
hotel_df["Country"]= fifth['Country']
hotel_df['Lat'] = fifth['Latitude']
hotel_df['Lng'] = fifth['Longitude']
hotel_df["Humidity"] = fifth["Humidity"]

hotel_df['Hotel Name'] = ""
hotel_df

                       City Country    Lat     Lng  Humidity Hotel Name
4                   rikitea      BR -17.71  -39.25        86
63                   palmer      NZ -46.19  168.86        63
110  grand river south east      BR -27.46  -53.93        81
142         haines junction      NZ -46.19  168.86        63
186                 rikitea      NZ -46.19  168.86        63
191            puerto ayora      SV  13.83  -88.92        88
330               cape town      BR   2.82  -60.67        73
371           san cristobal      NZ -46.19  168.86        63
384               hithadhoo      SV  13.83  -88.92        88
389             tuktoyaktuk      NZ -46.19  168.86        63
463                  atuona      NZ -46.19  168.86        63
464                ambilobe      NZ -46.19  168.86        63
470             provideniya      BR -17.71  -39.25        86
516              sao filipe      NZ -46.19  168.86        63
540                acapulco      GW  11.28  -15.83        68

In [7]:
params = {
    "radius": 5000,
    "types": "hotel",
    "key": g_key
}

target_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    long = row["Lng"]
    city = row["City"]
    country = row['Country']
    humidity = row['Humidity']
    
    params["location"] = f"{lat},{long}"

    response = requests.get(target_url,params)
    
    response_json = response.json()
    
    try:
        hotelname = response_json["results"][0]["name"]
        print(f"Closest hotel to {city} at {lat},{long} is {hotelname}.")
        hotel_df.loc[index, "Hotel Name"] =  hotelname
        
        
    except:
        print(f"skipping {row['City']}")
    print("---------------------")

Closest hotel to rikitea at -17.71,-39.25 is Caravelas.
---------------------
Closest hotel to palmer at -46.19,168.86 is Gore.
---------------------
Closest hotel to grand river south east at -27.46,-53.93 is Três Passos.
---------------------
Closest hotel to haines junction at -46.19,168.86 is Gore.
---------------------
Closest hotel to rikitea at -46.19,168.86 is Gore.
---------------------
Closest hotel to puerto ayora at 13.83,-88.92 is Tejutepeque.
---------------------
Closest hotel to cape town at 2.82,-60.67 is Boa Vista.
---------------------
Closest hotel to san cristobal at -46.19,168.86 is Gore.
---------------------
Closest hotel to hithadhoo at 13.83,-88.92 is Tejutepeque.
---------------------
Closest hotel to tuktoyaktuk at -46.19,168.86 is Gore.
---------------------
Closest hotel to atuona at -46.19,168.86 is Gore.
---------------------
Closest hotel to ambilobe at -46.19,168.86 is Gore.
---------------------
Closest hotel to provideniya at -17.71,-39.25 is Caravelas.
---------------------
Closest hotel to sao filipe at -46.19,168.86 is Gore.
---------------------
Closest hotel to acapulco at 11.28,-15.83 is Bubaque.
---------------------

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations2 = hotel_df[["Lat", "Lng"]]
humidity2 = hotel_df["Humidity"]

In [14]:
# Add marker layer ontop of heat map
fig = gmaps.figure(center=(48.0, 0.0), zoom_level=2)


marker_layer = gmaps.marker_layer(locations2, hover_text='', label='', info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


export("Heatmap_Outputs/marker_heatmap.html",views = [fig])

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))